// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/grep.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	After         int32                  `protobuf:"varint,3,opt,name=after,proto3" json:"after,omitempty"`
	Before        int32                  `protobuf:"varint,4,opt,name=before,proto3" json:"before,omitempty"`
	CountOnly     bool                   `protobuf:"varint,5,opt,name=count_only,json=countOnly,proto3" json:"count_only,omitempty"`
	Ignore        bool                   `protobuf:"varint,6,opt,name=ignore,proto3" json:"ignore,omitempty"`
	Invert        bool                   `protobuf:"varint,7,opt,name=invert,proto3" json:"invert,omitempty"`
	Fixed         bool                   `protobuf:"varint,8,opt,name=fixed,proto3" json:"fixed,omitempty"`
	LineNum       bool                   `protobuf:"varint,9,opt,name=line_num,json=lineNum,proto3" json:"line_num,omitempty"`
	LineOffset    int32                  `protobuf:"varint,10,opt,name=line_offset,json=lineOffset,proto3" json:"line_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrepRequest) Reset() {
	*x = GrepRequest{}
	mi := &file_proto_grep_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepRequest) ProtoMessage() {}

func (x *GrepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grep_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepRequest.ProtoReflect.Descriptor instead.
func (*GrepRequest) Descriptor() ([]byte, []int) {
	return file_proto_grep_proto_rawDescGZIP(), []int{0}
}

func (x *GrepRequest) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *GrepRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *GrepRequest) GetAfter() int32 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *GrepRequest) GetBefore() int32 {
	if x != nil {
		return x.Before
	}
	return 0
}

func (x *GrepRequest) GetCountOnly() bool {
	if x != nil {
		return x.CountOnly
	}
	return false
}

func (x *GrepRequest) GetIgnore() bool {
	if x != nil {
		return x.Ignore
	}
	return false
}

func (x *GrepRequest) GetInvert() bool {
	if x != nil {
		return x.Invert
	}
	return false
}

func (x *GrepRequest) GetFixed() bool {
	if x != nil {
		return x.Fixed
	}
	return false
}

func (x *GrepRequest) GetLineNum() bool {
	if x != nil {
		return x.LineNum
	}
	return false
}

func (x *GrepRequest) GetLineOffset() int32 {
	if x != nil {
		return x.LineOffset
	}
	return 0
}

type GrepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []string               `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrepResponse) Reset() {
	*x = GrepResponse{}
	mi := &file_proto_grep_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepResponse) ProtoMessage() {}

func (x *GrepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_grep_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepResponse.ProtoReflect.Descriptor instead.
func (*GrepResponse) Descriptor() ([]byte, []int) {
	return file_proto_grep_proto_rawDescGZIP(), []int{1}
}

func (x *GrepResponse) GetOutput() []string {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *GrepResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_grep_proto protoreflect.FileDescriptor

const file_proto_grep_proto_rawDesc = "" +
	"\n" +
	"\x10proto/grep.proto\x12\x04grep\"\x8c\x02\n" +
	"\vGrepRequest\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12\x14\n" +
	"\x05after\x18\x03 \x01(\x05R\x05after\x12\x16\n" +
	"\x06before\x18\x04 \x01(\x05R\x06before\x12\x1d\n" +
	"\n" +
	"count_only\x18\x05 \x01(\bR\tcountOnly\x12\x16\n" +
	"\x06ignore\x18\x06 \x01(\bR\x06ignore\x12\x16\n" +
	"\x06invert\x18\a \x01(\bR\x06invert\x12\x14\n" +
	"\x05fixed\x18\b \x01(\bR\x05fixed\x12\x19\n" +
	"\bline_num\x18\t \x01(\bR\alineNum\x12\x1f\n" +
	"\vline_offset\x18\n" +
	" \x01(\x05R\n" +
	"lineOffset\"<\n" +
	"\fGrepResponse\x12\x16\n" +
	"\x06output\x18\x01 \x03(\tR\x06output\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2<\n" +
	"\vGrepService\x12-\n" +
	"\x04Grep\x12\x11.grep.GrepRequest\x1a\x12.grep.GrepResponseB\x17Z\x15grpc-grep/proto;protob\x06proto3"

var (
	file_proto_grep_proto_rawDescOnce sync.Once
	file_proto_grep_proto_rawDescData []byte
)

func file_proto_grep_proto_rawDescGZIP() []byte {
	file_proto_grep_proto_rawDescOnce.Do(func() {
		file_proto_grep_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_grep_proto_rawDesc), len(file_proto_grep_proto_rawDesc)))
	})
	return file_proto_grep_proto_rawDescData
}

var file_proto_grep_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_grep_proto_goTypes = []any{
	(*GrepRequest)(nil),  // 0: grep.GrepRequest
	(*GrepResponse)(nil), // 1: grep.GrepResponse
}
var file_proto_grep_proto_depIdxs = []int32{
	0, // 0: grep.GrepService.Grep:input_type -> grep.GrepRequest
	1, // 1: grep.GrepService.Grep:output_type -> grep.GrepResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_grep_proto_init() }
func file_proto_grep_proto_init() {
	if File_proto_grep_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_grep_proto_rawDesc), len(file_proto_grep_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_grep_proto_goTypes,
		DependencyIndexes: file_proto_grep_proto_depIdxs,
		MessageInfos:      file_proto_grep_proto_msgTypes,
	}.Build()
	File_proto_grep_proto = out.File
	file_proto_grep_proto_goTypes = nil
	file_proto_grep_proto_depIdxs = nil
}
